### PR TITLE
DOMContentLoaded fix

### LINKED ISSUE #14: Tabex with iframe doesn't work when loaded after DOMContentLoaded event
Tabex, when configured with cross-domain via iframe, doesn't work when it was injected on the page after DOMContentLoaded event.

That's because this event was already fired, and won't fire never: https://github.com/nodeca/tabex/blob/master/lib/tunnel.js#L82, so no iframe is injected, no communication in tabex.

As possible fix we can check `window.readyState` and listen event only if it's `loading`.

### PR DESCRIPTION
**Pull request by Kukunin**
Fixes #14

### CODE REVIEW

**Comment by puzrin** [comment]
LGTM.

Just one comment - could you remove `/dist` folder from your PR and squash all to single commit?

**Comment by Kukunin** [comment]
Did you mean put `/dist` to gitignore? there is `dist` files in master branch, so I just followed the convention. I've added dist to `.gitignore` but that's not relevant to this PR 

About squash - you can do it yourself when you'll be merging this PR: https://help.github.com/articles/merging-a-pull-request/#merging-a-pull-request-on-github

**Comment by Kukunin** [comment]
Actually, it think I've understood what you meant - just exclude `dist/` folder changes from PR, because you rebuild it yourself.

**Comment by puzrin** [comment]
Yes, i rebuild those myself

**Comment by Kukunin** [comment]
ready

**Comment by puzrin** [comment]
Also, squashing via github leaves garbage in comment. It's better if you do it at your side.

**Comment by Kukunin** [comment]
done

**Comment by puzrin** [comment]
Released with your fix. Thanks!

**Pull request merged**
